version: '3'
services:
  my-mongo:
    image: mongo
    container_name: my-mongo
    ports: 
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=Pranav@123

  mongo-express:
      image: mongo-express
      restart: always
      depends_on:
        - my-mongo
      ports:
        - "8081:8081"
      environment:
        - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
        - ME_CONFIG_MONGODB_ADMINPASSWORD=Pranav%40123
        - ME_CONFIG_MONGODB_SERVER=my-mongo
